[package]
name = "Rust-WebServer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
validator = "0.16"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11.24", features = ["json"] }