[package]
name = "Rust-WebServer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
chrono = { version = "0.4", features = ["serde"] }
validator = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"